version: "3.2"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    logging:
      driver: "none"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./configs/nginx/certs:/etc/nginx/certs

  honest-authsrv:
    image: tomcat:latest
    ports:
      - "9090:9090"
    expose:
      - "443"
    volumes:
      - ./honest-authsrv/target/honest-authsrv.war:/usr/local/tomcat/webapps/honest-authsrv.war
      - ./honest-authsrv/keystore/honest-authsrv.p12:/usr/local/honest-authsrv.p12
      - type: bind
        source: ./configs/honest-authsrv/tomcat
        target: /usr/local/tomcat/conf
    container_name: honest-authsrv
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=9090,server=y,suspend=n"
      - VIRTUAL_HOST=honest-authsrv
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - HTTP_METHOD=nohttp

  malicious-authsrv:
    image: tomcat:latest
    ports:
      - "9091:9090"
    expose:
      - "80"
    volumes:
      - ./malicious-authsrv/target/malicious-authsrv.war:/usr/local/tomcat/webapps/malicious-authsrv.war
      - type: bind
        source: ./configs/malicious-authsrv/tomcat
        target: /usr/local/tomcat/conf
    container_name: malicious-authsrv
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=9090,server=y,suspend=n"
      - VIRTUAL_HOST=malicious-authsrv
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

  honest-client:
    build:
      context: ./
      dockerfile: Dockerfile-tomcat-ssl
    ports:
      - "9092:9090"
    expose:
      - "80"
    volumes:
      - ./honest-client/target/honest-client.war:/usr/local/tomcat/webapps/honest-client.war
      - type: bind
        source: ./configs/honest-client/tomcat
        target: /usr/local/tomcat/conf
    container_name: honest-client
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=9090,server=y,suspend=n"
      - VIRTUAL_HOST=honest-client
