version: "3"

services:
  oidc-server:
    image: tomcat:latest
    ports:
      - "8000:8080"
    volumes:
      - ./oidc-server/target/oidc-server.war:/usr/local/tomcat/webapps/oidc-server.war
    container_name: honest-oidc-server
        
  simple-web-app:
    image: tomcat:latest
    ports:
      - "8001:8080"
    volumes:
      - ./simple-web-app/target/simple-web-app.war:/usr/local/tomcat/webapps/simple-web-app.war
    container_name: oidc-client
