version: "3.2"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./configs/nginx/certs:/etc/nginx/certs

  honest-op:
    image: tomcat:latest
    ports:
      - "9090:9090"
    expose:
      - "443"
    volumes:
      - ./honest-op/target/honest-op.war:/usr/local/tomcat/webapps/honest-op.war
      - ./honest-op/keystore/tomcat.keystore:/usr/local/tomcat.keystore
      - type: bind
        source: ./configs/honest-op/tomcat
        target: /usr/local/tomcat/conf
    container_name: honest-op
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=9090,server=y,suspend=n"
      - VIRTUAL_HOST=honest-op
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - HTTP_METHOD=nohttp
    
  malicious-op:
    image: tomcat:latest
    ports:
      - "9091:9090"
    expose:
      - "80"
    volumes:
      - ./malicious-op/target/malicious-op.war:/usr/local/tomcat/webapps/malicious-op.war
      - type: bind
        source: ./configs/malicious-op/tomcat
        target: /usr/local/tomcat/conf
    container_name: malicious-op
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=9090,server=y,suspend=n"
      - VIRTUAL_HOST=malicious-op

  honest-client:
    image: tomcat:latest
    ports:
      - "9092:9090"
    expose:
      - "80"
    volumes:
      - ./honest-client/target/honest-client.war:/usr/local/tomcat/webapps/honest-client.war
      - type: bind
        source: ./configs/honest-client/tomcat
        target: /usr/local/tomcat/conf
    container_name: honest-client
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=9090,server=y,suspend=n"
      - VIRTUAL_HOST=honest-client
